In [2]:
import pandas as pd

Departments_data = {
'id': [1, 2, 3],
    'name': ['HR', 'Engineering', 'Sales']

}

Employees_data = {
    'id': [1, 2, 3, 4, 5, 6],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'dept_id': [1, 2, 1, 3, 2, 3]

}
departments_data_df = pd.DataFrame(Departments_data)
employees_data_df = pd.DataFrame(Employees_data)

In [3]:
departments_data_df

   id         name
0   1           HR
1   2  Engineering
2   3        Sales

In [4]:
employees_data_df

   id     name  dept_id
0   1    Alice        1
1   2      Bob        2
2   3  Charlie        1
3   4    David        3
4   5      Eve        2
5   6    Frank        3

In [5]:
hr_dept_id = departments_data_df.loc[departments_data_df['name'] == 'HR', 'id'].values[0] # HR department id
hr_dept_id

np.int64(1)

In [6]:
hr_employees = employees_data_df[employees_data_df['dept_id'] == hr_dept_id] # Independent nested query
hr_employees

   id     name  dept_id
0   1    Alice        1
2   3  Charlie        1

In [7]:
hr_employee_names = hr_employees['name']

In [8]:
hr_employee_names

0      Alice
2    Charlie
Name: name, dtype: object

In [9]:
hr_employee_names = employees_data_df[employees_data_df['dept_id'].isin(departments_data_df[departments_data_df['name']=='HR']['id'])]['name']

In [10]:
hr_employee_names

0      Alice
2    Charlie
Name: name, dtype: object

In [18]:
import sqlite3

conn = sqlite3.connect('test.db')

cursor = conn.cursor()

cursor.execute(""" CREATE TABLE IF NOT EXISTS users (
               id INT AUTO INCREMENT PRIMARY KEY,
               name VARCHAR (100),
               email VARCHAR (100)
)
""")

conn.commit()

In [28]:
cursor.execute("""INSERT INTO users(name, email) VALUES ("Aryam", "aryambajracharya00@gmail.com"), ("Aavash", "aavashgyani00@gmail.com")""")

In [29]:
conn.commit() # Commit the changes to the database and it will show kati commit garyo teti nai tala fetch hunxa

In [30]:
cursor.execute("SELECT * FROM users")
for row in cursor.fetchall():  # Multiple rows so we used loop
    print(row)

(None, 'Aryam', 'aryambajracharya00@gmail.com')
(None, 'Aryam', 'aryambajracharya00@gmail.com')
(None, 'Aavash', 'aavashrandi00@gmail.com')
(None, 'Aryam', 'aryambajracharya00@gmail.com')
(None, 'Aavash', 'aavashgyani00@gmail.com')